# Generated by Django 2.0.13 on 2019-06-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, choices=[('Teacher', '교사'), ('Student', '학생/학부모')], max_length=100, null=True),
        ),
    ]
